# -----------------------
#Github Action 
#
#Oleksandr Yurik
#------------------------
name: CICD-Action
env:
  BUCKET_NAME : "${{ github.sha }}"

on:
  push:
    branches: 
      - main

jobs:
  static-website-generation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2


      - name: Checking list of files
        run: ls -alF

      - name: Installing and configuring npm
        run: |
            npm install
            npm config delete prefix 
            npm config set prefix /usr/local
            npm install -g gatsby-cli

      - name: Checking list of files
        run: ls -alF

      - name: Setuping CONTENTFUL
        run: npm run setup -- --spaceId=${{secrets.CONTENTFUL_SPACE_ID}} --managementToken=${{secrets.CONTENTFUL_PERSONAL_AT}} --accessToken=${{secrets.CONTENT_DELIVERY_API_AT}}
            
      - name: Building
        run: gatsby build
            
      - name: Checking list of files
        run: ls -alF
