# -----------------------
#Github Action 
#
#Oleksandr Yurik
#------------------------
name: CICD-Action
env:
  BUCKET_NAME : "${{ github.sha }}"

on:
  push:
    branches: 
      - main

jobs:
  static-website-generation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2


      - name: Checking of path
        run: |
            cd alpacked-test-assignment-master/
            pwd
        
      - name: Installing npm
        run: npm install
        
      - name: Installing gatsby-cli
        run: npm i gatsby-cli
        
      - name: checking the ./public dir
        run: ls -alF
        
      - name: Setup by CONTENTFUL
        run: npm run setup -- --spaceId=${{secrets.CONTENTFUL_SPACE_ID}} --managementToken=${{secrets.CONTENTFUL_PERSONAL_AT}} --accessToken=${{secrets.CONTENT_DELIVERY_API_AT}}
     
      - name: Building
        run: gatsby build
        
      - name: checking the ./public dir
        run: ls -alF
          
